### ISSUE TITLE
Dependency error; no such file helm-buffers

### ISSUE THREAD

**Issue by conao3** [emacs-helm/helm-slime#7]
Hi! I found a dependency error.

This package `require` `helm-buffers`, but not download it by currently specified dependency.
So it produces below error.
```
Entering directory ‘/Users/conao/dev/repos/melpa/sandbox/elpa/helm-slime-20190702.1439/’
helm-slime.el:59:1:Error: Cannot open load file: No such file or directory, helm-buffers
```

There are two plans.
- specify `helm` as a dependency
- add `helm-buffers` to `helm-core`

So I can't fix it. For your information, I just reported.

**Comment by thierryvolpiatto** [comment]
Naoya Yamashita <notifications@github.com> writes:

>   * specify helm as a dependency

Done, thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by conao3** [comment]
Good. Thanks!
